apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingressroute
  namespace: gitea
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: rpcloud-intermediate-ca1-issuer
    cert-manager.io/common-name: gitea.local
spec:
  ingressClassName: traefik
  rules:
    - host: gitea.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 443
  tls:
    - hosts:
        - gitea.local
      secretName: gitea-cert-secret
